# Plugin: mysql/params_init.sh
# Fonction: ecriture des parametres par defaut dans la base SQL

########################################################################

req="DELETE FROM params WHERE 1;"
echo "${req}" |MYSQL

req="$(
cat<<EOF |sed -e "s/\(.*\) \(.*\)/INSERT INTO params (param_item,param_value) VALUES ('\1','\2');/g ; s/'NULL'/NULL/g"
DFH ${DFH:-NULL}
DLH ${DLH:-NULL}
YFD ${YFD:-NULL}
YLD ${YLD:-NULL}
MAX_SESSIONS ${MAX_SESSIONS:-NULL}
MAX_DURATION ${MAX_DURATION:-NULL}
MAX_TIME ${MAX_TIME:-NULL}
MAX_BYTES_CLASS0 ${MAX_BYTES_CLASS[0]:-NULL}
MAX_BYTES_CLASS1 ${MAX_BYTES_CLASS[1]:-NULL}
MAX_BYTES_CLASS2 ${MAX_BYTES_CLASS[2]:-NULL}
MAX_BYTES_CLASS3 ${MAX_BYTES_CLASS[3]:-NULL}
GUEST_N_MAX_SESSIONS ${GUEST_N_MAX_SESSIONS:-NULL}
GUEST_N_MAX_DURATION ${GUEST_N_MAX_DURATION:-NULL}
GUEST_N_MAX_TIME ${GUEST_N_MAX_TIME:-NULL}
GUEST_N_MAX_BYTES_CLASS0 ${GUEST_N_MAX_BYTES_CLASS[0]:-NULL}
GUEST_N_MAX_BYTES_CLASS1 ${GUEST_N_MAX_BYTES_CLASS[1]:-NULL}
GUEST_N_MAX_BYTES_CLASS2 ${GUEST_N_MAX_BYTES_CLASS[2]:-NULL}
GUEST_N_MAX_BYTES_CLASS3 ${GUEST_N_MAX_BYTES_CLASS[3]:-NULL}
GUEST_G_MAX_SESSIONS ${GUEST_G_MAX_SESSIONS:-NULL}
GUEST_G_MAX_DURATION ${GUEST_G_MAX_DURATION:-NULL}
GUEST_G_MAX_TIME ${GUEST_G_MAX_TIME:-NULL}
GUEST_G_MAX_BYTES_CLASS0 ${GUEST_G_MAX_BYTES_CLASS[0]:-NULL}
GUEST_G_MAX_BYTES_CLASS1 ${GUEST_G_MAX_BYTES_CLASS[1]:-NULL}
GUEST_G_MAX_BYTES_CLASS2 ${GUEST_G_MAX_BYTES_CLASS[2]:-NULL}
GUEST_G_MAX_BYTES_CLASS3 ${GUEST_G_MAX_BYTES_CLASS[3]:-NULL}
EOF
)"

echo "$req" |MYSQL

########################################################################

true
