#!/bin/bash
#
#%# family=contrib
#%# capabilities=autoconf

IPTABLES="/usr/bin/tsp -nf /sbin/iptables -nvxL counters"

if [ "$1" = "config" ]; then
cat<<EOF
graph_title Current trafic (full)
graph_vlabel Bits per \${graph_period}
graph_category uSpot
graph_info Current trafic
graph_args --base 1000
class0.label Class 0 trafic
class0.info Internal networks
class0.type DERIVE
class0.min 0
class0.cdef class0,8,*
class0.draw AREA
class1.label Class 1 trafic
class1.info Partners networks
class1.type DERIVE
class1.min 0
class1.cdef class1,8,*
class1.draw STACK
class2.label Class 2 trafic
class2.info Internet offload
class2.type DERIVE
class2.min 0
class2.cdef class2,8,*
class2.draw STACK
class3.label Class 3 trafic
class3.info Internet
class3.type DERIVE
class3.min 0
class3.cdef class3,8,*
class3.draw STACK
total.label Total
total.info Total
total.type DERIVE
total.min 0
total.cdef total,8,*
total.colour 000000
total.draw LINE2
EOF
exit 0
fi

eval $(sudo ${IPTABLES} |awk '{print $3" "$2}' |grep '^CLASS' |grep -v ' 0$' |sed -e 's/\(^CLASS\)\([0-9]\) \([0-9]*\)/\1\2=$(( ${\1\2} + \3 ))/g')

echo "class0.value ${CLASS0:-0}"
echo "class1.value ${CLASS1:-0}"
echo "class2.value ${CLASS2:-0}"
echo "class3.value ${CLASS3:-0}"
echo "total.value $(( ${CLASS0:-0} + ${CLASS1:-0} + ${CLASS2:-0} + ${CLASS3:-0} ))"
